# Generated by Django 3.2.14 on 2022-09-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DailyFlower',
            fields=[
                ('daily_flower_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flower_name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('flower_image', models.CharField(max_length=255)),
                ('flower_language', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'daily_flower',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flower_language', models.CharField(blank=True, max_length=255)),
                ('subject_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'subject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dear', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField()),
                ('login_count', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('profile_image', models.CharField(blank=True, max_length=255)),
                ('sex', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.tag')),
            ],
            options={
                'db_table': 'survey',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('sale_size', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.subject')),
            ],
            options={
                'db_table': 'sale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('popular_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('popular_date', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.user')),
            ],
            options={
                'db_table': 'popular',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.article')),
            ],
            options={
                'db_table': 'picture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('kind_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flower_image', models.CharField(blank=True, max_length=255)),
                ('kind_name', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.subject')),
            ],
            options={
                'db_table': 'kind',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.article')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.subject')),
            ],
            options={
                'db_table': 'hashtag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('following_user_user', models.ManyToManyField(related_name='follow_user_user', to='flowers.Follow')),
            ],
            options={
                'db_table': 'follow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FlowerLike',
            fields=[
                ('flower_like_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.kind')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.user')),
            ],
            options={
                'db_table': 'flower_like',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.user')),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('article_like_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.user')),
            ],
            options={
                'db_table': 'article_like',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.user'),
        ),
    ]
