# Generated by Django 3.2.14 on 2022-09-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerDislike',
            fields=[
                ('flower_dislike_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.kind')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.user')),
            ],
            options={
                'db_table': 'flower_dislike',
                'managed': True,
            },
        ),
    ]
